[build]
  base = "client"
  command = "cd .. && npm install && cd client && npm run build"
  publish = "dist"
  functions = "../netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[template.environment]
  TELEGRAM_BOT_TOKEN = "Bot token from @BotFather"
  TELEGRAM_GROUP_ID = "Telegram group/channel ID"
