services:
  - type: web
    name: portfolio
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    env: node
    buildFilter:
      paths:
        - client/**/*
    envVars:
      - key: NODE_ENV
        value: production
      - key: PATH
        value: /opt/render/project/node_modules/.bin:$PATH
