services:
  - type: static
    name: portfolio
    buildCommand: cd client && npm install --production=false && npm run build
    publishPath: client/dist
    envVars:
      - key: NODE_ENV
        value: production
    nodeVersion: 18
